FROM clojure:tools-deps

# Use non-root user
RUN useradd -ms /bin/bash myuser
USER myuser

# Here we can use users .m2 folder without hassle
WORKDIR /home/myuser

# Install deps
COPY deps.edn .

RUN clj -Sforce < /dev/null

# Copy source files
COPY . .

# Default command to run when container starts
CMD clj -m example.server

# No need to expose any ports here since Heroku ignores EXPOSE anyways.
